<?php

/**
 * @file
 * Contains chatbot_intent.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function chatbot_intent_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the chatbot_intent module.
    case 'help.page.chatbot_intent':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Chatbot plugin integration with Dialogflow') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function chatbot_intent_theme() {
  return [
    'chatbot_intent' => [
      'render element' => 'children',
    ],
  ];
}

